-- Seed: 299 Bundestagswahlkreise (Wahlkreiseinteilung 2025)
-- Source: Bundeswahlleiter (https://www.bundeswahlleiter.de)
-- Anlage zu § 2 Absatz 2 BWahlG – Einteilung des Wahlgebietes in Wahlkreise

INSERT INTO wahlkreise (id, name, bundesland) VALUES

-- Schleswig-Holstein (WK 1–11)
(1, 'Flensburg – Schleswig', 'Schleswig-Holstein'),
(2, 'Nordfriesland – Dithmarschen Nord', 'Schleswig-Holstein'),
(3, 'Steinburg – Dithmarschen Süd', 'Schleswig-Holstein'),
(4, 'Rendsburg-Eckernförde', 'Schleswig-Holstein'),
(5, 'Kiel', 'Schleswig-Holstein'),
(6, 'Plön – Neumünster', 'Schleswig-Holstein'),
(7, 'Pinneberg', 'Schleswig-Holstein'),
(8, 'Segeberg – Stormarn-Mitte', 'Schleswig-Holstein'),
(9, 'Ostholstein – Stormarn-Nord', 'Schleswig-Holstein'),
(10, 'Herzogtum Lauenburg – Stormarn-Süd', 'Schleswig-Holstein'),
(11, 'Lübeck', 'Schleswig-Holstein'),

-- Mecklenburg-Vorpommern (WK 12–17)
(12, 'Schwerin – Ludwigslust-Parchim I – Nordwestmecklenburg I', 'Mecklenburg-Vorpommern'),
(13, 'Ludwigslust-Parchim II – Nordwestmecklenburg II – Landkreis Rostock I', 'Mecklenburg-Vorpommern'),
(14, 'Rostock – Landkreis Rostock II', 'Mecklenburg-Vorpommern'),
(15, 'Vorpommern-Rügen – Vorpommern-Greifswald I', 'Mecklenburg-Vorpommern'),
(16, 'Mecklenburgische Seenplatte I – Vorpommern-Greifswald II', 'Mecklenburg-Vorpommern'),
(17, 'Mecklenburgische Seenplatte II – Landkreis Rostock III', 'Mecklenburg-Vorpommern'),

-- Hamburg (WK 18–23)
(18, 'Hamburg-Mitte', 'Hamburg'),
(19, 'Hamburg-Altona', 'Hamburg'),
(20, 'Hamburg-Eimsbüttel', 'Hamburg'),
(21, 'Hamburg-Nord', 'Hamburg'),
(22, 'Hamburg-Wandsbek', 'Hamburg'),
(23, 'Hamburg-Bergedorf – Harburg', 'Hamburg'),

-- Niedersachsen (WK 24–53)
(24, 'Aurich – Emden', 'Niedersachsen'),
(25, 'Unterems', 'Niedersachsen'),
(26, 'Friesland – Wilhelmshaven – Wittmund', 'Niedersachsen'),
(27, 'Oldenburg – Ammerland', 'Niedersachsen'),
(28, 'Delmenhorst – Wesermarsch – Oldenburg-Land', 'Niedersachsen'),
(29, 'Cuxhaven – Stade II', 'Niedersachsen'),
(30, 'Stade I – Rotenburg II', 'Niedersachsen'),
(31, 'Mittelems', 'Niedersachsen'),
(32, 'Cloppenburg – Vechta', 'Niedersachsen'),
(33, 'Diepholz – Nienburg I', 'Niedersachsen'),
(34, 'Osterholz – Verden', 'Niedersachsen'),
(35, 'Rotenburg I – Heidekreis', 'Niedersachsen'),
(36, 'Harburg', 'Niedersachsen'),
(37, 'Lüchow-Dannenberg – Lüneburg', 'Niedersachsen'),
(38, 'Osnabrück-Land', 'Niedersachsen'),
(39, 'Stadt Osnabrück', 'Niedersachsen'),
(40, 'Bad Bentheim – Grafschaft Bentheim', 'Niedersachsen'),
(41, 'Stadt Hannover I', 'Niedersachsen'),
(42, 'Stadt Hannover II', 'Niedersachsen'),
(43, 'Hannover-Land I', 'Niedersachsen'),
(44, 'Hannover-Land II', 'Niedersachsen'),
(45, 'Celle – Uelzen', 'Niedersachsen'),
(46, 'Gifhorn – Peine', 'Niedersachsen'),
(47, 'Hameln-Pyrmont – Holzminden', 'Niedersachsen'),
(48, 'Hildesheim', 'Niedersachsen'),
(49, 'Salzgitter – Wolfenbüttel', 'Niedersachsen'),
(50, 'Braunschweig', 'Niedersachsen'),
(51, 'Helmstedt – Wolfsburg', 'Niedersachsen'),
(52, 'Goslar – Northeim – Osterode', 'Niedersachsen'),
(53, 'Göttingen', 'Niedersachsen'),

-- Bremen (WK 54–55)
(54, 'Bremen I', 'Bremen'),
(55, 'Bremen II – Bremerhaven', 'Bremen'),

-- Brandenburg (WK 56–65)
(56, 'Prignitz – Ostprignitz-Ruppin – Havelland I', 'Brandenburg'),
(57, 'Uckermark – Barnim I', 'Brandenburg'),
(58, 'Oberhavel – Havelland II', 'Brandenburg'),
(59, 'Märkisch-Oderland – Barnim II', 'Brandenburg'),
(60, 'Brandenburg an der Havel – Potsdam-Mittelmark I – Havelland III – Teltow-Fläming I', 'Brandenburg'),
(61, 'Potsdam – Potsdam-Mittelmark II – Teltow-Fläming II', 'Brandenburg'),
(62, 'Dahme-Spreewald – Teltow-Fläming III – Oberspreewald-Lausitz I', 'Brandenburg'),
(63, 'Frankfurt (Oder) – Oder-Spree', 'Brandenburg'),
(64, 'Cottbus – Spree-Neiße', 'Brandenburg'),
(65, 'Elbe-Elster – Oberspreewald-Lausitz II', 'Brandenburg'),

-- Sachsen-Anhalt (WK 66–74)
(66, 'Altmark', 'Sachsen-Anhalt'),
(67, 'Börde – Jerichower Land', 'Sachsen-Anhalt'),
(68, 'Harz', 'Sachsen-Anhalt'),
(69, 'Magdeburg', 'Sachsen-Anhalt'),
(70, 'Dessau – Wittenberg', 'Sachsen-Anhalt'),
(71, 'Anhalt', 'Sachsen-Anhalt'),
(72, 'Mansfeld', 'Sachsen-Anhalt'),
(73, 'Halle (Saale)', 'Sachsen-Anhalt'),
(74, 'Burgenland – Saalekreis', 'Sachsen-Anhalt'),

-- Berlin (WK 75–86)
(75, 'Berlin-Mitte', 'Berlin'),
(76, 'Berlin-Pankow', 'Berlin'),
(77, 'Berlin-Reinickendorf', 'Berlin'),
(78, 'Berlin-Spandau – Charlottenburg Nord', 'Berlin'),
(79, 'Berlin-Steglitz-Zehlendorf', 'Berlin'),
(80, 'Berlin-Charlottenburg-Wilmersdorf', 'Berlin'),
(81, 'Berlin-Tempelhof-Schöneberg', 'Berlin'),
(82, 'Berlin-Neukölln', 'Berlin'),
(83, 'Berlin-Friedrichshain-Kreuzberg – Prenzlauer Berg Ost', 'Berlin'),
(84, 'Berlin-Treptow-Köpenick', 'Berlin'),
(85, 'Berlin-Marzahn-Hellersdorf', 'Berlin'),
(86, 'Berlin-Lichtenberg', 'Berlin'),

-- Nordrhein-Westfalen (WK 87–150)
(87, 'Aachen I', 'Nordrhein-Westfalen'),
(88, 'Aachen II', 'Nordrhein-Westfalen'),
(89, 'Heinsberg', 'Nordrhein-Westfalen'),
(90, 'Düren', 'Nordrhein-Westfalen'),
(91, 'Rhein-Erft-Kreis I', 'Nordrhein-Westfalen'),
(92, 'Euskirchen – Rhein-Erft-Kreis II', 'Nordrhein-Westfalen'),
(93, 'Köln I', 'Nordrhein-Westfalen'),
(94, 'Köln II', 'Nordrhein-Westfalen'),
(95, 'Köln III', 'Nordrhein-Westfalen'),
(96, 'Köln IV', 'Nordrhein-Westfalen'),
(97, 'Bonn', 'Nordrhein-Westfalen'),
(98, 'Rhein-Sieg-Kreis I', 'Nordrhein-Westfalen'),
(99, 'Rhein-Sieg-Kreis II', 'Nordrhein-Westfalen'),
(100, 'Oberbergischer Kreis', 'Nordrhein-Westfalen'),
(101, 'Rheinisch-Bergischer Kreis', 'Nordrhein-Westfalen'),
(102, 'Leverkusen – Köln V', 'Nordrhein-Westfalen'),
(103, 'Wuppertal I', 'Nordrhein-Westfalen'),
(104, 'Wuppertal II – Solingen', 'Nordrhein-Westfalen'),
(105, 'Remscheid', 'Nordrhein-Westfalen'),
(106, 'Mettmann I', 'Nordrhein-Westfalen'),
(107, 'Mettmann II', 'Nordrhein-Westfalen'),
(108, 'Düsseldorf I', 'Nordrhein-Westfalen'),
(109, 'Düsseldorf II', 'Nordrhein-Westfalen'),
(110, 'Neuss I', 'Nordrhein-Westfalen'),
(111, 'Neuss II', 'Nordrhein-Westfalen'),
(112, 'Mönchengladbach', 'Nordrhein-Westfalen'),
(113, 'Krefeld I – Neuss III', 'Nordrhein-Westfalen'),
(114, 'Krefeld II – Wesel II', 'Nordrhein-Westfalen'),
(115, 'Viersen', 'Nordrhein-Westfalen'),
(116, 'Kleve', 'Nordrhein-Westfalen'),
(117, 'Wesel I', 'Nordrhein-Westfalen'),
(118, 'Duisburg I', 'Nordrhein-Westfalen'),
(119, 'Duisburg II', 'Nordrhein-Westfalen'),
(120, 'Oberhausen – Wesel III', 'Nordrhein-Westfalen'),
(121, 'Mülheim – Essen I', 'Nordrhein-Westfalen'),
(122, 'Essen II', 'Nordrhein-Westfalen'),
(123, 'Essen III', 'Nordrhein-Westfalen'),
(124, 'Recklinghausen I', 'Nordrhein-Westfalen'),
(125, 'Recklinghausen II', 'Nordrhein-Westfalen'),
(126, 'Gelsenkirchen', 'Nordrhein-Westfalen'),
(127, 'Bottrop – Recklinghausen III', 'Nordrhein-Westfalen'),
(128, 'Borken I', 'Nordrhein-Westfalen'),
(129, 'Borken II – Coesfeld II', 'Nordrhein-Westfalen'),
(130, 'Coesfeld I – Steinfurt I', 'Nordrhein-Westfalen'),
(131, 'Steinfurt II', 'Nordrhein-Westfalen'),
(132, 'Steinfurt III', 'Nordrhein-Westfalen'),
(133, 'Münster', 'Nordrhein-Westfalen'),
(134, 'Warendorf', 'Nordrhein-Westfalen'),
(135, 'Gütersloh I', 'Nordrhein-Westfalen'),
(136, 'Bielefeld – Gütersloh II', 'Nordrhein-Westfalen'),
(137, 'Herford – Minden-Lübbecke II', 'Nordrhein-Westfalen'),
(138, 'Minden-Lübbecke I', 'Nordrhein-Westfalen'),
(139, 'Lippe I', 'Nordrhein-Westfalen'),
(140, 'Höxter – Lippe II', 'Nordrhein-Westfalen'),
(141, 'Paderborn', 'Nordrhein-Westfalen'),
(142, 'Herne – Bochum II', 'Nordrhein-Westfalen'),
(143, 'Bochum I', 'Nordrhein-Westfalen'),
(144, 'Dortmund I', 'Nordrhein-Westfalen'),
(145, 'Dortmund II', 'Nordrhein-Westfalen'),
(146, 'Unna I', 'Nordrhein-Westfalen'),
(147, 'Hamm – Unna II', 'Nordrhein-Westfalen'),
(148, 'Soest', 'Nordrhein-Westfalen'),
(149, 'Hochsauerlandkreis', 'Nordrhein-Westfalen'),
(150, 'Siegen-Wittgenstein – Olpe', 'Nordrhein-Westfalen'),

-- Sachsen (WK 151–166)
(151, 'Nordsachsen', 'Sachsen'),
(152, 'Leipzig I', 'Sachsen'),
(153, 'Leipzig II', 'Sachsen'),
(154, 'Leipzig III', 'Sachsen'),
(155, 'Leipzig-Land', 'Sachsen'),
(156, 'Meißen', 'Sachsen'),
(157, 'Bautzen I', 'Sachsen'),
(158, 'Görlitz', 'Sachsen'),
(159, 'Sächsische Schweiz-Osterzgebirge', 'Sachsen'),
(160, 'Dresden I', 'Sachsen'),
(161, 'Dresden II – Bautzen II', 'Sachsen'),
(162, 'Mittelsachsen', 'Sachsen'),
(163, 'Chemnitz', 'Sachsen'),
(164, 'Chemnitzer Umland – Erzgebirgskreis II', 'Sachsen'),
(165, 'Erzgebirgskreis I', 'Sachsen'),
(166, 'Zwickau', 'Sachsen'),

-- Thüringen (WK 167–174)
(167, 'Eichsfeld – Nordhausen – Kyffhäuserkreis', 'Thüringen'),
(168, 'Eisenach – Wartburgkreis – Unstrut-Hainich-Kreis', 'Thüringen'),
(169, 'Jena – Sömmerda – Weimarer Land I', 'Thüringen'),
(170, 'Gotha – Ilm-Kreis', 'Thüringen'),
(171, 'Erfurt – Weimar – Weimarer Land II', 'Thüringen'),
(172, 'Gera – Greiz – Altenburger Land', 'Thüringen'),
(173, 'Saalfeld-Rudolstadt – Saale-Holzland-Kreis – Saale-Orla-Kreis', 'Thüringen'),
(174, 'Suhl – Schmalkalden-Meiningen – Hildburghausen – Sonneberg', 'Thüringen'),

-- Hessen (WK 175–196)
(175, 'Waldeck', 'Hessen'),
(176, 'Kassel', 'Hessen'),
(177, 'Werra-Meißner – Hersfeld-Rotenburg', 'Hessen'),
(178, 'Schwalm-Eder', 'Hessen'),
(179, 'Marburg', 'Hessen'),
(180, 'Lahn-Dill', 'Hessen'),
(181, 'Gießen', 'Hessen'),
(182, 'Fulda', 'Hessen'),
(183, 'Main-Kinzig – Wetterau II – Schotten', 'Hessen'),
(184, 'Hochtaunus', 'Hessen'),
(185, 'Wetterau I', 'Hessen'),
(186, 'Rheingau-Taunus – Limburg', 'Hessen'),
(187, 'Wiesbaden', 'Hessen'),
(188, 'Hanau', 'Hessen'),
(189, 'Main-Taunus', 'Hessen'),
(190, 'Frankfurt am Main I', 'Hessen'),
(191, 'Frankfurt am Main II', 'Hessen'),
(192, 'Groß-Gerau', 'Hessen'),
(193, 'Offenbach', 'Hessen'),
(194, 'Darmstadt', 'Hessen'),
(195, 'Odenwald', 'Hessen'),
(196, 'Bergstraße', 'Hessen'),

-- Rheinland-Pfalz (WK 197–211)
(197, 'Neuwied', 'Rheinland-Pfalz'),
(198, 'Ahrweiler', 'Rheinland-Pfalz'),
(199, 'Koblenz', 'Rheinland-Pfalz'),
(200, 'Mosel/Rhein-Hunsrück', 'Rheinland-Pfalz'),
(201, 'Bitburg', 'Rheinland-Pfalz'),
(202, 'Trier', 'Rheinland-Pfalz'),
(203, 'Montabaur', 'Rheinland-Pfalz'),
(204, 'Mainz', 'Rheinland-Pfalz'),
(205, 'Worms', 'Rheinland-Pfalz'),
(206, 'Alzey – Worms', 'Rheinland-Pfalz'),
(207, 'Bad Kreuznach', 'Rheinland-Pfalz'),
(208, 'Kaiserslautern', 'Rheinland-Pfalz'),
(209, 'Pirmasens', 'Rheinland-Pfalz'),
(210, 'Neustadt – Speyer', 'Rheinland-Pfalz'),
(211, 'Ludwigshafen/Frankenthal', 'Rheinland-Pfalz'),

-- Bayern (WK 212–257)
(212, 'Altötting', 'Bayern'),
(213, 'Erding – Ebersberg', 'Bayern'),
(214, 'Freising', 'Bayern'),
(215, 'Fürstenfeldbruck', 'Bayern'),
(216, 'Ingolstadt', 'Bayern'),
(217, 'München-Nord', 'Bayern'),
(218, 'München-Ost', 'Bayern'),
(219, 'München-Süd', 'Bayern'),
(220, 'München-West/Mitte', 'Bayern'),
(221, 'München-Land', 'Bayern'),
(222, 'Rosenheim', 'Bayern'),
(223, 'Bad Tölz-Wolfratshausen – Miesbach', 'Bayern'),
(224, 'Starnberg – Landsberg am Lech', 'Bayern'),
(225, 'Traunstein', 'Bayern'),
(226, 'Weilheim', 'Bayern'),
(227, 'Deggendorf', 'Bayern'),
(228, 'Landshut', 'Bayern'),
(229, 'Passau', 'Bayern'),
(230, 'Rottal-Inn', 'Bayern'),
(231, 'Straubing', 'Bayern'),
(232, 'Amberg', 'Bayern'),
(233, 'Regensburg', 'Bayern'),
(234, 'Schwandorf', 'Bayern'),
(235, 'Weiden', 'Bayern'),
(236, 'Bamberg', 'Bayern'),
(237, 'Bayreuth', 'Bayern'),
(238, 'Coburg', 'Bayern'),
(239, 'Hof', 'Bayern'),
(240, 'Kulmbach', 'Bayern'),
(241, 'Ansbach', 'Bayern'),
(242, 'Erlangen', 'Bayern'),
(243, 'Fürth', 'Bayern'),
(244, 'Nürnberg-Nord', 'Bayern'),
(245, 'Nürnberg-Süd', 'Bayern'),
(246, 'Roth', 'Bayern'),
(247, 'Aschaffenburg', 'Bayern'),
(248, 'Bad Kissingen', 'Bayern'),
(249, 'Main-Spessart', 'Bayern'),
(250, 'Schweinfurt', 'Bayern'),
(251, 'Würzburg', 'Bayern'),
(252, 'Augsburg-Stadt', 'Bayern'),
(253, 'Augsburg-Land', 'Bayern'),
(254, 'Donau-Ries', 'Bayern'),
(255, 'Neu-Ulm', 'Bayern'),
(256, 'Oberallgäu', 'Bayern'),
(257, 'Ostallgäu', 'Bayern'),

-- Saarland (WK 258–261)
(258, 'Saarbrücken', 'Saarland'),
(259, 'Saarlouis', 'Saarland'),
(260, 'St. Wendel', 'Saarland'),
(261, 'Homburg', 'Saarland'),

-- Baden-Württemberg (WK 262–299)
(262, 'Stuttgart I', 'Baden-Württemberg'),
(263, 'Stuttgart II', 'Baden-Württemberg'),
(264, 'Böblingen', 'Baden-Württemberg'),
(265, 'Esslingen', 'Baden-Württemberg'),
(266, 'Nürtingen', 'Baden-Württemberg'),
(267, 'Göppingen', 'Baden-Württemberg'),
(268, 'Ludwigsburg', 'Baden-Württemberg'),
(269, 'Waiblingen', 'Baden-Württemberg'),
(270, 'Backnang – Schwäbisch Gmünd', 'Baden-Württemberg'),
(271, 'Heilbronn', 'Baden-Württemberg'),
(272, 'Schwäbisch Hall – Hohenlohe', 'Baden-Württemberg'),
(273, 'Neckar-Zaber', 'Baden-Württemberg'),
(274, 'Pforzheim', 'Baden-Württemberg'),
(275, 'Calw', 'Baden-Württemberg'),
(276, 'Karlsruhe-Stadt', 'Baden-Württemberg'),
(277, 'Karlsruhe-Land', 'Baden-Württemberg'),
(278, 'Rastatt', 'Baden-Württemberg'),
(279, 'Heidelberg', 'Baden-Württemberg'),
(280, 'Mannheim', 'Baden-Württemberg'),
(281, 'Odenwald – Tauber', 'Baden-Württemberg'),
(282, 'Rhein-Neckar', 'Baden-Württemberg'),
(283, 'Bruchsal – Schwetzingen', 'Baden-Württemberg'),
(284, 'Offenburg', 'Baden-Württemberg'),
(285, 'Freiburg', 'Baden-Württemberg'),
(286, 'Lörrach – Müllheim', 'Baden-Württemberg'),
(287, 'Emmendingen – Lahr', 'Baden-Württemberg'),
(288, 'Rottweil – Tuttlingen', 'Baden-Württemberg'),
(289, 'Schwarzwald-Baar', 'Baden-Württemberg'),
(290, 'Konstanz', 'Baden-Württemberg'),
(291, 'Waldshut', 'Baden-Württemberg'),
(292, 'Reutlingen', 'Baden-Württemberg'),
(293, 'Tübingen', 'Baden-Württemberg'),
(294, 'Ulm', 'Baden-Württemberg'),
(295, 'Biberach', 'Baden-Württemberg'),
(296, 'Bodensee', 'Baden-Württemberg'),
(297, 'Ravensburg', 'Baden-Württemberg'),
(298, 'Zollernalb – Sigmaringen', 'Baden-Württemberg'),
(299, 'Balingen – Hechingen', 'Baden-Württemberg')
;

-- Total: 299 Wahlkreise
-- Note: geometry column will be populated later via GeoJSON import
